# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`App-GhaProve`
	:runtime-requirement    [ :on "perl 5.006"^^:CpanId ];
	:runtime-requirement    [ :on "Test::Harness 2.40"^^:CpanId ];
	:configure-requirement  [ :on "ExtUtils::MakeMaker 6.64"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

